/*
 * VOICEVOX Engine
 *
 * VOICEVOX の音声合成エンジンです。
 *
 * The version of the OpenAPI document: 0.21.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace VoicevoxClient.Generated.Model
{
    /// <summary>
    /// BodySingFrameVolumeSingFrameVolumePost
    /// </summary>
    [DataContract(Name = "Body_sing_frame_volume_sing_frame_volume_post")]
    public class BodySingFrameVolumeSingFrameVolumePost : IEquatable<BodySingFrameVolumeSingFrameVolumePost>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BodySingFrameVolumeSingFrameVolumePost" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BodySingFrameVolumeSingFrameVolumePost()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BodySingFrameVolumeSingFrameVolumePost" /> class.
        /// </summary>
        /// <param name="score">score (required).</param>
        /// <param name="frameAudioQuery">frameAudioQuery (required).</param>
        public BodySingFrameVolumeSingFrameVolumePost(Score score = default, FrameAudioQuery frameAudioQuery = default)
        {
            // to ensure "score" is required (not null)
            if (score == null)
            {
                throw new ArgumentNullException(
                    "score is a required property for BodySingFrameVolumeSingFrameVolumePost and cannot be null");
            }

            Score = score;
            // to ensure "frameAudioQuery" is required (not null)
            if (frameAudioQuery == null)
            {
                throw new ArgumentNullException(
                    "frameAudioQuery is a required property for BodySingFrameVolumeSingFrameVolumePost and cannot be null");
            }

            FrameAudioQuery = frameAudioQuery;
        }

        /// <summary>
        /// Gets or Sets Score
        /// </summary>
        [DataMember(Name = "score", IsRequired = true, EmitDefaultValue = false)]
        public Score Score { get; set; }

        /// <summary>
        /// Gets or Sets FrameAudioQuery
        /// </summary>
        [DataMember(Name = "frame_audio_query", IsRequired = true, EmitDefaultValue = false)]
        public FrameAudioQuery FrameAudioQuery { get; set; }

        /// <summary>
        /// Returns true if BodySingFrameVolumeSingFrameVolumePost instances are equal
        /// </summary>
        /// <param name="input">Instance of BodySingFrameVolumeSingFrameVolumePost to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BodySingFrameVolumeSingFrameVolumePost input)
        {
            if (input == null)
            {
                return false;
            }

            return
                (
                    Score == input.Score ||
                    (Score != null &&
                     Score.Equals(input.Score))
                ) &&
                (
                    FrameAudioQuery == input.FrameAudioQuery ||
                    (FrameAudioQuery != null &&
                     FrameAudioQuery.Equals(input.FrameAudioQuery))
                );
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BodySingFrameVolumeSingFrameVolumePost {\n");
            sb.Append("  Score: ").Append(Score).Append("\n");
            sb.Append("  FrameAudioQuery: ").Append(FrameAudioQuery).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as BodySingFrameVolumeSingFrameVolumePost);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (Score != null)
                {
                    hashCode = hashCode * 59 + Score.GetHashCode();
                }

                if (FrameAudioQuery != null)
                {
                    hashCode = hashCode * 59 + FrameAudioQuery.GetHashCode();
                }

                return hashCode;
            }
        }
    }
}