/*
 * VOICEVOX Engine
 *
 * VOICEVOX の音声合成エンジンです。
 *
 * The version of the OpenAPI document: 0.21.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace VoicevoxClient.Generated.Model
{
    /// <summary>
    /// CORSの許可モード
    /// </summary>
    /// <value>CORSの許可モード</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CorsPolicyMode
    {
        /// <summary>
        /// Enum All for value: all
        /// </summary>
        [EnumMember(Value = "all")] All = 1,

        /// <summary>
        /// Enum Localapps for value: localapps
        /// </summary>
        [EnumMember(Value = "localapps")] Localapps = 2
    }
}