/*
 * VOICEVOX Engine
 *
 * VOICEVOX の音声合成エンジンです。
 *
 * The version of the OpenAPI document: 0.21.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace VoicevoxClient.Generated.Model
{
    /// <summary>
    /// ダウンロード可能な音声ライブラリの情報
    /// </summary>
    [DataContract(Name = "DownloadableLibraryInfo")]
    public class DownloadableLibraryInfo : IEquatable<DownloadableLibraryInfo>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DownloadableLibraryInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DownloadableLibraryInfo()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DownloadableLibraryInfo" /> class.
        /// </summary>
        /// <param name="name">音声ライブラリの名前 (required).</param>
        /// <param name="uuid">音声ライブラリのUUID (required).</param>
        /// <param name="varVersion">音声ライブラリのバージョン (required).</param>
        /// <param name="downloadUrl">音声ライブラリのダウンロードURL (required).</param>
        /// <param name="bytes">音声ライブラリのバイト数 (required).</param>
        /// <param name="speakers">speakers (required).</param>
        public DownloadableLibraryInfo(string name = default,
            string uuid = default,
            string varVersion = default,
            string downloadUrl = default,
            int bytes = default,
            List<LibrarySpeaker> speakers = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException(
                    "name is a required property for DownloadableLibraryInfo and cannot be null");
            }

            Name = name;
            // to ensure "uuid" is required (not null)
            if (uuid == null)
            {
                throw new ArgumentNullException(
                    "uuid is a required property for DownloadableLibraryInfo and cannot be null");
            }

            Uuid = uuid;
            // to ensure "varVersion" is required (not null)
            if (varVersion == null)
            {
                throw new ArgumentNullException(
                    "varVersion is a required property for DownloadableLibraryInfo and cannot be null");
            }

            VarVersion = varVersion;
            // to ensure "downloadUrl" is required (not null)
            if (downloadUrl == null)
            {
                throw new ArgumentNullException(
                    "downloadUrl is a required property for DownloadableLibraryInfo and cannot be null");
            }

            DownloadUrl = downloadUrl;
            Bytes = bytes;
            // to ensure "speakers" is required (not null)
            if (speakers == null)
            {
                throw new ArgumentNullException(
                    "speakers is a required property for DownloadableLibraryInfo and cannot be null");
            }

            Speakers = speakers;
        }

        /// <summary>
        /// 音声ライブラリの名前
        /// </summary>
        /// <value>音声ライブラリの名前</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// 音声ライブラリのUUID
        /// </summary>
        /// <value>音声ライブラリのUUID</value>
        [DataMember(Name = "uuid", IsRequired = true, EmitDefaultValue = false)]
        public string Uuid { get; set; }

        /// <summary>
        /// 音声ライブラリのバージョン
        /// </summary>
        /// <value>音声ライブラリのバージョン</value>
        [DataMember(Name = "version", IsRequired = true, EmitDefaultValue = false)]
        public string VarVersion { get; set; }

        /// <summary>
        /// 音声ライブラリのダウンロードURL
        /// </summary>
        /// <value>音声ライブラリのダウンロードURL</value>
        [DataMember(Name = "download_url", IsRequired = true, EmitDefaultValue = false)]
        public string DownloadUrl { get; set; }

        /// <summary>
        /// 音声ライブラリのバイト数
        /// </summary>
        /// <value>音声ライブラリのバイト数</value>
        [DataMember(Name = "bytes", IsRequired = true, EmitDefaultValue = false)]
        public int Bytes { get; set; }

        /// <summary>
        /// Gets or Sets Speakers
        /// </summary>
        [DataMember(Name = "speakers", IsRequired = true, EmitDefaultValue = false)]
        public List<LibrarySpeaker> Speakers { get; set; }

        /// <summary>
        /// Returns true if DownloadableLibraryInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of DownloadableLibraryInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DownloadableLibraryInfo input)
        {
            if (input == null)
            {
                return false;
            }

            return
                (
                    Name == input.Name ||
                    (Name != null &&
                     Name.Equals(input.Name))
                ) &&
                (
                    Uuid == input.Uuid ||
                    (Uuid != null &&
                     Uuid.Equals(input.Uuid))
                ) &&
                (
                    VarVersion == input.VarVersion ||
                    (VarVersion != null &&
                     VarVersion.Equals(input.VarVersion))
                ) &&
                (
                    DownloadUrl == input.DownloadUrl ||
                    (DownloadUrl != null &&
                     DownloadUrl.Equals(input.DownloadUrl))
                ) &&
                (
                    Bytes == input.Bytes ||
                    Bytes.Equals(input.Bytes)
                ) &&
                (
                    Speakers == input.Speakers ||
                    (Speakers != null &&
                     input.Speakers != null &&
                     Speakers.SequenceEqual(input.Speakers))
                );
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DownloadableLibraryInfo {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Uuid: ").Append(Uuid).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("  DownloadUrl: ").Append(DownloadUrl).Append("\n");
            sb.Append("  Bytes: ").Append(Bytes).Append("\n");
            sb.Append("  Speakers: ").Append(Speakers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as DownloadableLibraryInfo);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (Name != null)
                {
                    hashCode = hashCode * 59 + Name.GetHashCode();
                }

                if (Uuid != null)
                {
                    hashCode = hashCode * 59 + Uuid.GetHashCode();
                }

                if (VarVersion != null)
                {
                    hashCode = hashCode * 59 + VarVersion.GetHashCode();
                }

                if (DownloadUrl != null)
                {
                    hashCode = hashCode * 59 + DownloadUrl.GetHashCode();
                }

                hashCode = hashCode * 59 + Bytes.GetHashCode();
                if (Speakers != null)
                {
                    hashCode = hashCode * 59 + Speakers.GetHashCode();
                }

                return hashCode;
            }
        }
    }
}