/*
 * VOICEVOX Engine
 *
 * VOICEVOX の音声合成エンジンです。
 *
 * The version of the OpenAPI document: 0.21.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace VoicevoxClient.Generated.Model
{
    /// <summary>
    /// 音素の情報
    /// </summary>
    [DataContract(Name = "FramePhoneme")]
    public class FramePhoneme : IEquatable<FramePhoneme>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FramePhoneme" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FramePhoneme()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FramePhoneme" /> class.
        /// </summary>
        /// <param name="phoneme">音素 (required).</param>
        /// <param name="frameLength">音素のフレーム長 (required).</param>
        /// <param name="noteId">noteId.</param>
        public FramePhoneme(string phoneme = default, int frameLength = default, string noteId = default)
        {
            // to ensure "phoneme" is required (not null)
            if (phoneme == null)
            {
                throw new ArgumentNullException("phoneme is a required property for FramePhoneme and cannot be null");
            }

            Phoneme = phoneme;
            FrameLength = frameLength;
            NoteId = noteId;
        }

        /// <summary>
        /// 音素
        /// </summary>
        /// <value>音素</value>
        [DataMember(Name = "phoneme", IsRequired = true, EmitDefaultValue = false)]
        public string Phoneme { get; set; }

        /// <summary>
        /// 音素のフレーム長
        /// </summary>
        /// <value>音素のフレーム長</value>
        [DataMember(Name = "frame_length", IsRequired = true, EmitDefaultValue = false)]
        public int FrameLength { get; set; }

        /// <summary>
        /// Gets or Sets NoteId
        /// </summary>
        [DataMember(Name = "note_id", EmitDefaultValue = true)]
        public string NoteId { get; set; }

        /// <summary>
        /// Returns true if FramePhoneme instances are equal
        /// </summary>
        /// <param name="input">Instance of FramePhoneme to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FramePhoneme input)
        {
            if (input == null)
            {
                return false;
            }

            return
                (
                    Phoneme == input.Phoneme ||
                    (Phoneme != null &&
                     Phoneme.Equals(input.Phoneme))
                ) &&
                (
                    FrameLength == input.FrameLength ||
                    FrameLength.Equals(input.FrameLength)
                ) &&
                (
                    NoteId == input.NoteId ||
                    (NoteId != null &&
                     NoteId.Equals(input.NoteId))
                );
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FramePhoneme {\n");
            sb.Append("  Phoneme: ").Append(Phoneme).Append("\n");
            sb.Append("  FrameLength: ").Append(FrameLength).Append("\n");
            sb.Append("  NoteId: ").Append(NoteId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as FramePhoneme);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (Phoneme != null)
                {
                    hashCode = hashCode * 59 + Phoneme.GetHashCode();
                }

                hashCode = hashCode * 59 + FrameLength.GetHashCode();
                if (NoteId != null)
                {
                    hashCode = hashCode * 59 + NoteId.GetHashCode();
                }

                return hashCode;
            }
        }
    }
}