/*
 * VOICEVOX Engine
 *
 * VOICEVOX の音声合成エンジンです。
 *
 * The version of the OpenAPI document: 0.21.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace VoicevoxClient.Generated.Model
{
    /// <summary>
    /// エンジンのアップデート情報
    /// </summary>
    [DataContract(Name = "UpdateInfo")]
    public class UpdateInfo : IEquatable<UpdateInfo>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdateInfo()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateInfo" /> class.
        /// </summary>
        /// <param name="varVersion">エンジンのバージョン名 (required).</param>
        /// <param name="descriptions">descriptions (required).</param>
        /// <param name="contributors">contributors.</param>
        public UpdateInfo(string varVersion = default,
            List<string> descriptions = default,
            List<string> contributors = default)
        {
            // to ensure "varVersion" is required (not null)
            if (varVersion == null)
            {
                throw new ArgumentNullException("varVersion is a required property for UpdateInfo and cannot be null");
            }

            VarVersion = varVersion;
            // to ensure "descriptions" is required (not null)
            if (descriptions == null)
            {
                throw new ArgumentNullException(
                    "descriptions is a required property for UpdateInfo and cannot be null");
            }

            Descriptions = descriptions;
            Contributors = contributors;
        }

        /// <summary>
        /// エンジンのバージョン名
        /// </summary>
        /// <value>エンジンのバージョン名</value>
        [DataMember(Name = "version", IsRequired = true, EmitDefaultValue = false)]
        public string VarVersion { get; set; }

        /// <summary>
        /// Gets or Sets Descriptions
        /// </summary>
        [DataMember(Name = "descriptions", IsRequired = true, EmitDefaultValue = false)]
        public List<string> Descriptions { get; set; }

        /// <summary>
        /// Gets or Sets Contributors
        /// </summary>
        [DataMember(Name = "contributors", EmitDefaultValue = false)]
        public List<string> Contributors { get; set; }

        /// <summary>
        /// Returns true if UpdateInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdateInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateInfo input)
        {
            if (input == null)
            {
                return false;
            }

            return
                (
                    VarVersion == input.VarVersion ||
                    (VarVersion != null &&
                     VarVersion.Equals(input.VarVersion))
                ) &&
                (
                    Descriptions == input.Descriptions ||
                    (Descriptions != null &&
                     input.Descriptions != null &&
                     Descriptions.SequenceEqual(input.Descriptions))
                ) &&
                (
                    Contributors == input.Contributors ||
                    (Contributors != null &&
                     input.Contributors != null &&
                     Contributors.SequenceEqual(input.Contributors))
                );
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateInfo {\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("  Descriptions: ").Append(Descriptions).Append("\n");
            sb.Append("  Contributors: ").Append(Contributors).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as UpdateInfo);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (VarVersion != null)
                {
                    hashCode = hashCode * 59 + VarVersion.GetHashCode();
                }

                if (Descriptions != null)
                {
                    hashCode = hashCode * 59 + Descriptions.GetHashCode();
                }

                if (Contributors != null)
                {
                    hashCode = hashCode * 59 + Contributors.GetHashCode();
                }

                return hashCode;
            }
        }
    }
}